name: Merge latest-charts branch to master
on:
  workflow_run:
    workflows: ["Latest Charts Auto-PR"]
    types:
      - completed

jobs:
  merge-branch:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge latest-charts -> master
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: master
          github_token: ${{ github.token }}
