name: auto-merge

on:
  workflow_run:
    workflows: ["Merge Latest-Charts Into Master"]
    types:
      - completed

jobs:
  auto-merge:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: master
          github-token: ${{ secrets.TOKEN }}
