name: Merge latest-charts branch to master
on:
  push:
    branches:
      - 'latest-charts-*'
  workflow_run:
    workflows: ["Opensource Charts Validation"]
    types:
      - completed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  merge-branch:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge latest-charts -> master
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: master
          github_token: ${{ github.token }}